# Generated by Django 4.1.2 on 2022-10-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='data_inscricao',
            new_name='data_matricula',
        ),
    ]
