# Generated by Django 4.1.2 on 2022-10-29 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_data_inscricao_matricula_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
    ]
